# Generated by Django 6.0.1 on 2026-01-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_expedient_delete_cases'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
