# Generated by Django 6.0.1 on 2026-01-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_cliente_client'),
        ('lawyers', '0002_remove_lawyer_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='abogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='lawyers.lawyer'),
        ),
    ]
