# Generated by Django 6.0.1 on 2026-02-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_abogado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
