# Generated by Django 6.0.1 on 2026-01-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='client',
        ),
    ]
